#!/usr/bin/env python3
"""
STEPPED555 — Technical drawing (DWG-001).

Auto-generated by make-drawing. Edit freely.
To update metadata: edit _STEP_FILE / _TITLE / etc. in the cog block, then run:
  cog -r stepped555.py   (pip install cogapp)

Run:  uv run python stepped555.py
"""
import os as _os
from draftwright import build_drawing

# Available for lint-suggestion snippets (dwg.lint_summary()); unused otherwise.
from build123d_drafting import Dimension, HoleCallout, Leader  # noqa: F401

# ── Config (auto-updated by cog) ──────────────────────────────────────────────
# [[[cog
# ── Config: edit these, then run `cog -r <script>.py` to update ────────────
_STEP_FILE = '/tmp/stepped555.step'
_TITLE     = 'STEPPED555'
_NUMBER    = 'DWG-001'
_TOLERANCE = 'ISO 2768-m'
_DRAWN_BY  = ''
_PMI       = 'off'   # 'off' | 'report' | 'annotate'
_SCALE     = None   # None = auto; e.g. 5 for 5:1, 0.5 for 1:2
_PAGE      = None   # None = auto; e.g. 'A3' or (297, 210)
try:
    cog  # NameError → not under cog
    for _k, _v in [
        ('STEP_FILE', repr(_STEP_FILE)), ('TITLE', repr(_TITLE)),
        ('NUMBER', repr(_NUMBER)), ('TOLERANCE', repr(_TOLERANCE)),
        ('DRAWN_BY', repr(_DRAWN_BY)), ('PMI', repr(_PMI)),
        ('SCALE', repr(_SCALE)), ('PAGE', repr(_PAGE)),
    ]:
        cog.outl(f'{_k} = {_v}')
except NameError:
    pass
# ]]]
STEP_FILE = '/tmp/stepped555.step'
TITLE = 'STEPPED555'
NUMBER = 'DWG-001'
TOLERANCE = 'ISO 2768-m'
DRAWN_BY = ''
PMI = 'off'
SCALE = None
PAGE = None
# [[[end]]]
# ── Build drawing (detect-only 4-view layout; dimensions added below) ──────────
_stem = _os.path.splitext(__file__)[0]
dwg = build_drawing(
    STEP_FILE,
    out=_stem,
    title=TITLE,
    number=NUMBER,
    tolerance=TOLERANCE,
    drawn_by=DRAWN_BY,
    pmi=PMI,
    scale=SCALE,
    page=PAGE,
    auto_dims=False,   # detect-only — the intent verbs below add every dimension
)

# ── Customise here — runs BEFORE export, so edits land in the output ───────────
# Prefer domain edits (the intent verbs below) over page mechanics (at / Leader);
# the engine places annotations automatically — say WHAT, not WHERE.
# dwg.model().features     → detected feature IR for domain edits
# dwg.dimension(f, param, role=…, pin=True, priority=…)  → feature-backed dimension
# dwg.locate(f, pin=True)  → feature-backed location dimension
# dwg.annotations()        → {name: type} of every named annotation
# dwg.get_annotation(name) → the named annotation object, or None
# dwg.remove(name) / dwg.add(obj, name)
# dwg.pin(name) / dwg.unpin(name)  → fix a placement so repair never moves it
# dwg.lint_summary()       → {passed, score, by_code, issues:[…suggestion]}
# dwg.repair()             → auto-fix mechanically-fixable lint (never worsens)
# dwg.add_view(name, shape, camera, up, position)  → section / auxiliary view
# dwg.items / dwg.views / dwg.at(view,x,y,z) / dwg.view_bounds(view)  → low-level escape
# dwg.place_dim(...)       → deprecated raw page-coordinate dimension escape hatch
# Example — add a pinned feature-backed linear dimension:
#   env = next(f for f in dwg.model().features if f.kind == 'envelope')
#   dwg.dimension(env, 'length', role='width', side='below', pin=True)

# ── Reconstruct the drawing at intent level (record → finalize, #426) ─────────
# The verbs RECORD intents inside `with dwg.deferred()`; on block exit finalize()
# drains them through the auto-pass's own batch solvers, so the reconstruction
# reaches auto-pass placement quality — not greedy live placement. Comment any
# single line to drop exactly that intent; comment a whole block to stop
# dimensioning that feature. The build above is detect-only, so nothing is drawn
# twice. Kinds with no verb yet are flagged inline — build_drawing(auto_dims=True)
# recovers the full automatic drawing for those.
#
with dwg.deferred():
    # features[0]  envelope @ (0, 0, 0)
    f = dwg.model().features[0]
    dwg.dimension(f, "length", role="width")   # 80
    dwg.dimension(f, "length", role="height")   # 30
    dwg.dimension(f, "length", role="depth")   # 60
    # features[1]  step_level @ (0, 0, -15)
    f = dwg.model().features[1]
    dwg.dimension(f, "length", role="step_height")   # prismatic height ladder
    dwg.dimension(f, "length", role="step_position")   # 20

# finalize() (auto-run on the `with` exit above, and again by export) batch-solved
# the recorded intents; repair() is now just a peephole net — it never worsens the
# sheet (#426 Phase 5).
dwg.repair()

# ── Export ────────────────────────────────────────────────────────────────────
svg_path, dxf_path = dwg.export(_stem)
print(f"SVG -> {svg_path}")
print(f"DXF -> {dxf_path}")
