"""The part-drawing compiler IR (ADR 0008).

A stable intermediate representation (`PartModel` of `Feature` objects exposing
`DimParameter`s) sitting between the feature *detectors* (front-ends adapting the
recognition heuristics) and a *dimensioning planner* (back-end). The narrow waist
that lets new shapes be new types, not new branches.

**Status:** the ADR 0008 convergence is **complete — one path** (2026-06-30).
`build_part_model` runs once per build from `_analyse`'s single feature
inventory (Amendment 5); every render pass consumes the IR — the
`annotations/from_model.py` renderers (turned/diameters, centre marks,
envelope, step lengths, height ladder, PMI, GD&T, …), the hole/section passes
(`annotations/holes.py` / `sections.py` via `plan_dimensions` /
`plan_sections`), and page/scale sizing (Amendment 8). Coverage lint alone
reads recognised geometry, by design (ground truth, not the plan).

- :mod:`.ir` — the IR: `DimParameter`, `Datum`, `Frame`, the `Feature` protocol,
  the concrete feature types, and `PartModel`.
- :mod:`.detect` — `build_part_model`: run the detectors, collect features.
- :mod:`.planner` — `plan_dimensions`: convention rules over `DimParameter`s.
"""

from __future__ import annotations

from draftwright.model.declare import (
    boss,
    chamfer,
    channel,
    control_frame,
    datum,
    double_d_bore,
    envelope,
    external_spur_gear,
    fillet,
    finish,
    flat,
    groove,
    hole,
    measured_dimension,
    note,
    pad,
    pattern,
    plate,
    pocket,
    pocket_pattern,
    polygonal_boss,
    polygonal_stock,
    rotational,
    slot,
    slot_pattern,
    step,
    step_level,
)
from draftwright.model.detect import build_part_model, build_pmi_features
from draftwright.model.ir import (
    AUTHORED_DIMENSION_KINDS,
    AuthoredDimension,
    BossFeature,
    ChamferFeature,
    ChannelFeature,
    ControlFrame,
    Datum,
    DatumRef,
    DimensionParameterId,
    DimParameter,
    EnvelopeFeature,
    ExternalSpurGearFeature,
    Feature,
    FilletFeature,
    FlatFeature,
    Frame,
    GrooveFeature,
    HoleFeature,
    LevelSupport,
    PadFeature,
    ParameterId,
    PartModel,
    PatternFeature,
    PlateFeature,
    PmiFeature,
    PocketFeature,
    PocketPatternFeature,
    PolygonalBossFeature,
    PolygonalStockFeature,
    RotationalFeature,
    SlotFeature,
    SlotPatternFeature,
    StepFeature,
    StepLevelFeature,
    display,
)
from draftwright.model.planner import (
    AddressableDimension,
    DimensionGroup,
    DimensionId,
    PlannedDimension,
    SectionPlan,
    plan_dimensions,
    plan_sections,
)
from draftwright.view_plan import UncoveredViewRequirement, ViewPlanIncomplete

__all__ = [
    "AuthoredDimension",
    "AUTHORED_DIMENSION_KINDS",
    "BossFeature",
    "ChamferFeature",
    "ChannelFeature",
    "ControlFrame",
    "FilletFeature",
    "FlatFeature",
    "GrooveFeature",
    "Datum",
    "DatumRef",
    "DimParameter",
    "EnvelopeFeature",
    "ExternalSpurGearFeature",
    "AddressableDimension",
    "DimensionGroup",
    "DimensionId",
    "UncoveredViewRequirement",
    "ViewPlanIncomplete",
    "Feature",
    "Frame",
    "HoleFeature",
    "LevelSupport",
    "DimensionParameterId",
    "ParameterId",
    "PartModel",
    "PadFeature",
    "PatternFeature",
    "PmiFeature",
    "PocketFeature",
    "PocketPatternFeature",
    "RotationalFeature",
    "PlannedDimension",
    "SlotFeature",
    "SlotPatternFeature",
    "StepFeature",
    "PlateFeature",
    "PolygonalBossFeature",
    "PolygonalStockFeature",
    "StepLevelFeature",
    "measured_dimension",
    "build_part_model",
    "build_pmi_features",
    "boss",
    "double_d_bore",
    "chamfer",
    "channel",
    "fillet",
    "control_frame",
    "datum",
    "envelope",
    "external_spur_gear",
    "finish",
    "flat",
    "groove",
    "hole",
    "note",
    "pattern",
    "pad",
    "plate",
    "rotational",
    "pocket",
    "pocket_pattern",
    "polygonal_boss",
    "polygonal_stock",
    "slot",
    "slot_pattern",
    "step",
    "step_level",
    "display",
    "SectionPlan",
    "plan_dimensions",
    "plan_sections",
]
