"""Drawing attribution and multi-format export behavior."""

import warnings
from pathlib import Path

import pytest
from build123d import Box

from draftwright import build_drawing, make_drawing


@pytest.fixture
def plain_box_dwg(shared_drawing):
    return shared_drawing("box_60x40x20")


class TestDraftwrightAttribution:
    """draftwright self-attribution in the title block + clickable SVG link."""

    def test_author_appends_draftwright(self):
        from draftwright.annotations._sheet_furniture import _attribution_author

        assert _attribution_author("P. Fremantle") == "P. Fremantle / draftwright"

    def test_author_defaults_to_draftwright(self):
        from draftwright.annotations._sheet_furniture import _attribution_author

        assert _attribution_author("") == "draftwright"
        assert _attribution_author(None) == "draftwright"
        assert _attribution_author("   ") == "draftwright"

    def test_link_rect_sits_over_the_drawn_by_cell(self, plain_box_dwg):
        # The hyperlink rect must cover the "drawn by" cell of the *rendered*
        # title block: bottom row (half the two-row block height), from the
        # drawn-by cell's left edge to the block's right edge. The left edge is
        # derived from the block's public cell bbox (#139); everything is asserted
        # against the placed block's bounding box so it catches drift if the rect
        # or the upstream TitleBlock layout ever diverge.
        dwg = plain_box_dwg
        tb = dwg.get_annotation("title_block")
        # The rect rides the title-block annotation (#699 slice d), not the drawing.
        x0, y0, x1, y1 = tb.draftwright_link_rect
        bb = tb.bounding_box()
        cell = tb.drawn_by_cell_bbox()  # build-frame; block min corner is at bb.min
        # Both edges come from the block's own cell bbox, not its extents: under
        # the ISO 7200 layout the drawn-by cell no longer reaches the right edge
        # (DATE, REV and SHEET sit to its right) and is one row of four, not two.
        assert x0 == pytest.approx(bb.min.X + cell["min_x"], abs=0.5)
        assert x1 == pytest.approx(bb.min.X + cell["max_x"], abs=0.5)
        assert y0 == pytest.approx(bb.min.Y + cell["min_y"], abs=0.5)
        assert y1 == pytest.approx(bb.min.Y + cell["max_y"], abs=0.5)
        assert 0 < x0 < x1 <= dwg.page_w and 0 < y0 < y1 <= dwg.page_h

    def test_add_svg_hyperlink_injects_anchor(self, tmp_path):
        from draftwright.export import _DRAFTWRIGHT_URL, add_svg_hyperlink

        svg = tmp_path / "x.svg"
        svg.write_text(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -100 200 100"><g/></svg>',
            encoding="utf-8",
        )
        add_svg_hyperlink(str(svg), (150.0, 10.0, 190.0, 18.0))
        out = svg.read_text(encoding="utf-8")
        assert "xmlns:xlink" in out  # namespace declared so xlink:href is valid
        assert f'href="{_DRAFTWRIGHT_URL}"' in out
        # page (x, y) -> svg (x, -y): rect top-left = (150, -18), size 40 x 8
        assert 'x="150.000" y="-18.000" width="40.000" height="8.000"' in out
        assert 'pointer-events="all"' in out

    def test_export_svg_carries_the_clickable_link(self, tmp_path):
        dwg = build_drawing(Box(60, 40, 20))
        _p = dwg.export(str(tmp_path / "out"), formats=("svg", "dxf"))
        svg_path = _p["svg"]
        svg = Path(svg_path).read_text(encoding="utf-8")
        assert "github.com/pzfreo/draftwright" in svg
        assert "<a " in svg and "</a>" in svg

    def test_export_embeds_metadata_in_svg_and_dxf(self, tmp_path):
        dwg = build_drawing(Box(60, 40, 20), drawn_by="P. Fremantle")
        _p = dwg.export(str(tmp_path / "m"), formats=("svg", "dxf"))
        svg_path = _p["svg"]
        dxf_path = _p["dxf"]
        svg = Path(svg_path).read_text(encoding="utf-8")
        assert "<dc:creator>draftwright</dc:creator>" in svg
        assert "Generated by draftwright" in svg
        dxf = Path(dxf_path).read_text(encoding="utf-8", errors="ignore")
        assert "GeneratedBy" in dxf and "draftwright" in dxf

    def test_export_pdf_carries_clickable_link(self, tmp_path):
        # Exercises the load-bearing SVG->PDF coordinate transform + reportlab
        # link annotation. svglib + reportlab are core deps (pure Python, no
        # native cairo), so this runs on every platform. The URI may live in a
        # FlateDecode object stream, so scan the decompressed streams too.
        import re as _re
        import zlib

        dwg = build_drawing(Box(60, 40, 20))
        # The PDF export includes the link annotation.
        pdf_path = dwg.export(str(tmp_path / "p"), formats=("pdf",))["pdf"]
        data = Path(pdf_path).read_bytes()
        found = b"pzfreo/draftwright" in data
        for m in _re.finditer(rb"stream\r?\n(.*?)\r?\nendstream", data, _re.S):
            try:
                chunk = zlib.decompress(m.group(1))
            except Exception:
                continue
            if b"/URI" in chunk and b"pzfreo" in chunk:
                found = True
        assert found, "PDF must embed a clickable draftwright URI link annotation"

    def test_export_pdf_notes_and_tables_are_searchable_unicode_text(self, tmp_path):
        import pypdfium2 as pdfium

        dwg = build_drawing(Box(60, 40, 20), auto_dims=False)
        dwg.note("INSPECT SURFACE ±0.1", (65, 55), name="inspection_note")
        dwg.note("ROTATED NOTE", (100, 55), rotation=45, name="rotated_note")
        dwg.add_table(
            [("NOTES", "SIZE"), ("DEBURR", "⌀5 ±0.1")],
            name="notes_table",
        )

        pdf_path = dwg.export(str(tmp_path / "searchable"), formats=("pdf",))["pdf"]
        pdf = pdfium.PdfDocument(pdf_path)
        try:
            page = pdf[0]
            text_page = page.get_textpage()
            extracted = text_page.get_text_range()
            first_char_box = text_page.get_charbox(extracted.index("INSPECT SURFACE"))
            rotated_char_box = text_page.get_charbox(extracted.index("ROTATED NOTE"))
        finally:
            pdf.close()

        assert "INSPECT SURFACE ±0.1" in extracted
        assert "ROTATED NOTE" in extracted
        assert "NOTES" in extracted and "DEBURR" in extracted
        # The visible drafting font's longstanding CAD compatibility glyph is
        # ø for source ⌀; copied text must match what the engineer sees.
        assert "ø5 ±0.1" in extracted
        # It is not merely an off-page search index: the selectable character
        # geometry lies over the visible note on the drawing.
        note_box = dwg.get_annotation("inspection_note").bounding_box()
        k = 72.0 / 25.4
        left, bottom, right, top = first_char_box
        assert left < note_box.max.X * k and right > note_box.min.X * k
        assert bottom < note_box.max.Y * k and top > note_box.min.Y * k
        rotated_box = dwg.get_annotation("rotated_note").bounding_box()
        left, bottom, right, top = rotated_char_box
        assert left < rotated_box.max.X * k and right > rotated_box.min.X * k
        assert bottom < rotated_box.max.Y * k and top > rotated_box.min.Y * k

    def test_export_pdf_does_not_silently_discard_semantic_text(self, tmp_path, monkeypatch):
        from reportlab.pdfgen.canvas import Canvas

        dwg = build_drawing(Box(30, 20, 10), auto_dims=False)
        dwg.note("MUST BE SEARCHABLE", (50, 50))

        def fail_semantic_text(_self, _text):
            raise RuntimeError("semantic text failure")

        monkeypatch.setattr(Canvas, "drawText", fail_semantic_text)
        with pytest.raises(RuntimeError, match="semantic text failure"):
            dwg.export(str(tmp_path / "broken"), formats=("pdf",))


class TestExportFormats:
    """The unified export(formats=...) → {format: path} API + PNG raster export
    (permissive pypdfium2 + Pillow; SVG→PDF→PNG, no native cairo)."""

    def test_export_returns_dict_of_requested_paths(self, tmp_path):
        dwg = build_drawing(Box(60, 40, 20))
        paths = dwg.export(str(tmp_path / "d"), formats=("svg", "dxf", "pdf", "png"))
        assert set(paths) == {"svg", "dxf", "pdf", "png"}
        for fmt, p in paths.items():
            assert Path(p).exists() and Path(p).stat().st_size > 0, fmt
            assert p.endswith("." + fmt)

    def test_export_png_is_valid_and_cleans_intermediates(self, tmp_path):
        dwg = build_drawing(Box(60, 40, 20))
        paths = dwg.export(str(tmp_path / "p"), formats="png")  # single-format string accepted
        assert set(paths) == {"png"}
        assert Path(paths["png"]).read_bytes()[:8] == b"\x89PNG\r\n\x1a\n"  # PNG magic
        # the SVG + PDF written only to render the PNG are removed
        assert not (tmp_path / "p.svg").exists() and not (tmp_path / "p.pdf").exists()

    def test_png_export_does_not_clobber_existing_outputs(self, tmp_path):
        # #677 review (blocking): a later png-only export to the same stem must NOT overwrite
        # then delete an SVG/PDF an earlier export wrote — intermediates go to a temp dir.
        dwg = build_drawing(Box(60, 40, 20))
        stem = str(tmp_path / "part")
        dwg.export(stem, formats=("svg", "pdf"))
        svg, pdf = tmp_path / "part.svg", tmp_path / "part.pdf"
        svg_bytes, pdf_bytes = svg.read_bytes(), pdf.read_bytes()
        dwg.export(stem, formats="png")  # must not touch the existing svg/pdf
        assert (tmp_path / "part.png").exists()
        assert svg.exists() and svg.read_bytes() == svg_bytes  # untouched, not deleted
        assert pdf.exists() and pdf.read_bytes() == pdf_bytes

    def test_export_png_dpi_scales_the_raster(self, tmp_path):
        dwg = build_drawing(Box(60, 40, 20))
        lo = Path(dwg.export(str(tmp_path / "lo"), formats="png", dpi=72)["png"]).stat().st_size
        hi = Path(dwg.export(str(tmp_path / "hi"), formats="png", dpi=220)["png"]).stat().st_size
        assert hi > lo  # more pixels → a larger file

    def test_export_unknown_format_raises(self, tmp_path):
        dwg = build_drawing(Box(30, 20, 10))
        with pytest.raises(ValueError, match="unknown export format"):
            dwg.export(str(tmp_path / "x"), formats=("svg", "jpeg"))

    def test_export_format_is_case_insensitive(self, tmp_path):
        # #677 review: a single-string format must normalise like an iterable one.
        dwg = build_drawing(Box(30, 20, 10))
        assert set(dwg.export(str(tmp_path / "u"), formats="PNG")) == {"png"}
        assert set(dwg.export(str(tmp_path / "v"), formats=("SVG", "Dxf"))) == {"svg", "dxf"}

    def test_export_png_zero_dpi_raises(self, tmp_path):
        # #677 review: reject dpi<=0 before writing, so no intermediates are stranded.
        dwg = build_drawing(Box(30, 20, 10))
        with pytest.raises(ValueError, match="dpi > 0"):
            dwg.export(str(tmp_path / "z"), formats="png", dpi=0)

    def test_removed_export_forms_reject_before_writing_issue_2113(self, tmp_path):
        dwg = build_drawing(Box(30, 20, 10))
        stem = str(tmp_path / "removed")
        for kwargs in (
            {},
            {"formats": None},
            {"svg": True},
            {"dxf": True},
            {"formats": ("svg",), "svg": False},
        ):
            with pytest.raises(TypeError):
                dwg.export(stem, **kwargs)
        assert not list(tmp_path.glob("removed.*"))

    def test_one_shot_formats_iterable_is_exported_once(self, tmp_path):
        dwg = build_drawing(Box(30, 20, 10))
        paths = dwg.export(str(tmp_path / "gen"), formats=(f for f in ("svg", "dxf")))
        assert sorted(paths) == ["dxf", "svg"]
        assert all(Path(p).exists() for p in paths.values())

    def test_make_drawing_keeps_its_tuple_output(self, tmp_path):
        """The facade keeps its documented SVG/DXF tuple over explicit Drawing formats."""
        with warnings.catch_warnings():
            warnings.simplefilter("error", DeprecationWarning)
            svg, dxf = make_drawing(Box(30, 20, 10), out=str(tmp_path / "mk"))
        assert Path(svg).exists() and svg.endswith(".svg")
        assert Path(dxf).exists() and dxf.endswith(".dxf")


def test_preview_export_skips_lint_but_normal_export_keeps_it_issue_2209(tmp_path, monkeypatch):
    drawing = build_drawing(Box(20, 10, 5), page="A4", scale=1)

    def fail_if_linted():
        raise RuntimeError("export lint ran")

    monkeypatch.setattr(drawing, "_lint_and_log", fail_if_linted)
    paths = drawing.export(str(tmp_path / "preview"), formats=("svg",), lint=False)
    assert paths["svg"] == str(tmp_path / "preview.svg")
    assert (tmp_path / "preview.svg").is_file()

    with pytest.raises(RuntimeError, match="export lint ran"):
        drawing.export(str(tmp_path / "final"), formats=("svg",))
    assert not (tmp_path / "final.svg").exists()
