"""#1254: recognised conical chamfers survive the consumer and render non-redundantly."""

import warnings
from pathlib import Path
from unittest.mock import patch

import pytest
from b123d_recognisers import Chamfer
from build123d import Axis, Box, Cylinder, import_step
from build123d import chamfer as b3d_chamfer

from draftwright import Drawing, build_drawing
from draftwright.model import chamfer
from draftwright.model import detect as detect_module
from draftwright.model.detect import build_part_model
from draftwright.sheet_emit import generate_sheet_script

GRM03 = Path(__file__).parent / "fixtures" / "grm03_thumbwheel_drive_screw.step"


def _chamfer_features(drawing):
    return [feature for feature in drawing.model().features if feature.kind == "chamfer"]


def _chamfer_callouts(drawing):
    return {
        drawing.get_annotation(name).label: drawing.measurement_keys(name)
        for name in drawing.annotations()
        if name.startswith("m_chamfer")
    }


@pytest.fixture(scope="module")
def grm03_drawing():
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return build_drawing(import_step(GRM03), number="GRM-03")


def test_a_supplied_turned_chamfer_lowers_without_rescanning(monkeypatch):
    record = Chamfer(axis="z", leg1=0.3, leg2=0.3, angle=45.0, at=(0.0, 0.0, 19.85))

    def unexpected_rescan(_part):
        raise AssertionError("the consumer rescanned instead of lowering the supplied inventory")

    monkeypatch.setattr(detect_module, "recognise_chamfers", unexpected_rescan)
    model = build_part_model(
        Cylinder(5, 20),
        chamfers=(record,),
        fillets=(),
        rotational=(10.0, (), "z"),
    )

    assert [
        (feature.axis, feature.leg1, feature.leg2, feature.angle, feature.frame.origin)
        for feature in model.features
        if feature.kind == "chamfer"
    ] == [("z", 0.3, 0.3, 45.0, (0.0, 0.0, 19.85))]


def test_grm03_renders_two_requirements_with_all_three_measurement_identities(grm03_drawing):
    assert sorted(
        (feature.leg1, feature.leg2) for feature in _chamfer_features(grm03_drawing)
    ) == [
        (0.3, 0.3),
        (0.3, 0.3),
        (0.5, 0.5),
    ]

    callouts = _chamfer_callouts(grm03_drawing)
    assert set(callouts) == {"2× C0.3", "C0.5"}
    assert len(callouts["2× C0.3"]) == 2
    assert len(callouts["C0.5"]) == 1

    codes = {issue.code for issue in grm03_drawing.lint()}
    assert "chamfer_dropped" not in codes
    assert "plan_incomplete" not in codes


def test_grm03_sheet_source_round_trips_the_three_chamfers(tmp_path):
    script = generate_sheet_script(str(GRM03), out=str(tmp_path / "grm03"))
    source = Path(script).read_text(encoding="utf-8")
    assert source.count("= sheet.chamfer(") == 3
    assert "2× C0.3, C0.5" in source

    captured = {}
    with patch.object(Drawing, "export", lambda self, *a, **k: captured.setdefault("dwg", self)):
        exec(compile(source, script, "exec"), {})  # noqa: S102 — generated by this repository

    round_trip = captured["dwg"]
    assert sorted((feature.leg1, feature.leg2) for feature in _chamfer_features(round_trip)) == [
        (0.3, 0.3),
        (0.3, 0.3),
        (0.5, 0.5),
    ]
    assert set(_chamfer_callouts(round_trip)) == {"2× C0.3", "C0.5"}


def test_same_first_leg_does_not_collapse_different_chamfer_forms():
    plate = Box(90, 60, 20)
    edges = plate.edges().filter_by(Axis.Z).sort_by(lambda edge: edge.center().X + edge.center().Y)
    part = b3d_chamfer([edges[0], edges[-1]], 8)
    equal_leg = chamfer(axis="z", leg=8, at=(41, 26, 0))
    asymmetric = chamfer(axis="z", leg1=8, leg2=4, at=(-41, -26, 0))

    drawing = build_drawing(part, model=[equal_leg, asymmetric], number="X")
    callouts = _chamfer_callouts(drawing)

    assert set(callouts) == {"C8", "8 × 26.6°"}
    assert all(len(measurements) == 1 for measurements in callouts.values())

    # Deferred/subset rendering enumerates the full collapse before filtering. The equal-leg
    # group sorts second, so it must retain z1 when its asymmetric z0 sibling is not requested.
    edited = build_drawing(part, model=[equal_leg, asymmetric], auto_dims=False, number="X")
    with edited.deferred():
        edited.callout(equal_leg)
    assert [name for name in edited.annotations() if name.startswith("m_chamfer")] == [
        "m_chamfer_z1"
    ]
