"""#1281: recognised toroidal fillets survive the consumer and render non-redundantly."""

import warnings
from pathlib import Path
from unittest.mock import patch

import pytest
from b123d_recognisers import Fillet
from build123d import Cylinder, GeomType, Pos, export_step, fillet

from draftwright import Drawing, build_drawing
from draftwright.model import detect as detect_module
from draftwright.model.detect import build_part_model
from draftwright.sheet_emit import generate_sheet_script


def _rounded_shaft():
    shaft = Pos(0, 0, 20) * Cylinder(15, 40) + Pos(0, 0, 55) * Cylinder(8, 30)
    circular_edges = [edge for edge in shaft.edges() if edge.geom_type == GeomType.CIRCLE]
    return fillet(circular_edges, 0.8)


def _fillet_features(drawing):
    return [feature for feature in drawing.model().features if feature.kind == "fillet"]


def _fillet_callouts(drawing):
    return {
        drawing.get_annotation(name).label: drawing.measurement_keys(name)
        for name in drawing.annotations()
        if name.startswith("m_fillet")
    }


@pytest.fixture(scope="module")
def rounded_shaft_drawing():
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return build_drawing(_rounded_shaft(), number="X")


def test_a_supplied_turned_fillet_lowers_without_rescanning(monkeypatch):
    record = Fillet(axis="z", radius=0.8, at=(-4.8, 0.0, 19.8))

    def unexpected_rescan(_part):
        raise AssertionError("the consumer rescanned instead of lowering the supplied inventory")

    monkeypatch.setattr(detect_module, "recognise_fillets", unexpected_rescan)
    model = build_part_model(
        Cylinder(5, 20),
        chamfers=(),
        fillets=(record,),
        rotational=(10.0, (), "z"),
    )

    assert [
        (feature.axis, feature.radius, feature.frame.origin)
        for feature in model.features
        if feature.kind == "fillet"
    ] == [("z", 0.8, (-4.8, 0.0, 19.8))]


def test_rounded_shaft_renders_one_requirement_with_all_four_identities(
    rounded_shaft_drawing,
):
    records = rounded_shaft_drawing.recognition().fillets
    features = _fillet_features(rounded_shaft_drawing)
    assert [(feature.axis, feature.radius, feature.frame.origin) for feature in features] == [
        (record.axis, record.radius, record.at) for record in records
    ]
    assert len(features) == 4

    callouts = _fillet_callouts(rounded_shaft_drawing)
    assert set(callouts) == {"4× R0.8"}
    assert len(callouts["4× R0.8"]) == 4

    codes = {issue.code for issue in rounded_shaft_drawing.lint()}
    assert "fillet_dropped" not in codes
    assert "plan_incomplete" not in codes


def test_rounded_shaft_sheet_source_round_trips_the_four_fillets(tmp_path):
    step = tmp_path / "rounded-shaft.step"
    export_step(_rounded_shaft(), step)
    script = generate_sheet_script(str(step), out=str(tmp_path / "rounded-shaft"))
    source = Path(script).read_text(encoding="utf-8")
    assert source.count("= sheet.fillet(") == 4
    assert "4× R0.8" in source

    captured = {}
    with patch.object(Drawing, "export", lambda self, *a, **k: captured.setdefault("dwg", self)):
        exec(compile(source, script, "exec"), {})  # noqa: S102 — generated by this repository

    round_trip = captured["dwg"]
    assert [feature.radius for feature in _fillet_features(round_trip)] == [0.8] * 4
    callouts = _fillet_callouts(round_trip)
    assert set(callouts) == {"4× R0.8"}
    assert len(callouts["4× R0.8"]) == 4
