"""sheet_emit — the declarative ``Sheet``-DSL emitter (ADR 0011 Amendment 1, #461).

Mode 3 of the three authoring modes: *generate an editable beautiful-Python script*. Walk a
**detected** :class:`PartModel` and print a :class:`~draftwright.Sheet` script — one commentable
line per feature — that the user edits / comments-out / extends, then re-runs.

**Detected input only writes numbers (the part-seam form, ADR 0011 Amdt 1 decision).** For a STEP
file or a recovered solid the number *is* the ground truth, so a detected value is honest. We never
fabricate a build123d part to chase a number-free layer — a synthesised solid silently drops what
detection didn't model (chamfers, fillets, turned profiles) yet reads as authoritative. A caller who
*has* the objects (mode 3b) wires their real part into the seam and swaps the number lines for
``sheet.hole(obj)`` references — the emitter's numbers are a starting point, not a ceiling.

Kinds with no declarative verb yet (``step_level``/``rotational``/``pmi``) are flagged inline as
auto-dimensioned — never silently dropped. Fidelity: the script reproduces a lint-clean drawing of
the same features (the auto-pass runs over the declared model), not a byte copy of the detected sheet.
"""

from __future__ import annotations

from pathlib import Path

from build123d import Shape

from draftwright.builder import detect_part_model


def _n(v) -> float | int:
    """A tidy number: int when integral, else rounded to 3 dp."""
    v = round(float(v), 3)
    return int(v) if v == int(v) else v


def _pt(p) -> str:
    return "(" + ", ".join(str(_n(c)) for c in p) + ")"


def _hole_line(f) -> str:
    kw = [f"diameter={_n(f.diameter)}", f"at={_pt(f.frame.origin)}", f'axis="{f.frame.axis}"']
    if f.count and f.count > 1:
        kw.append(f"count={f.count}")
    if f.cbore:
        kw.append(f"cbore=({_n(f.cbore[0])}, {_n(f.cbore[1])})")
    if f.spotface:
        kw.append(f"spotface=({_n(f.spotface[0])}, {_n(f.spotface[1])})")
    line = f"sheet.hole({', '.join(kw)})"
    if not f.through and f.depth is not None:
        line += f".depth({_n(f.depth)})"
    return line


def _feature_line(f) -> str:
    k = f.kind
    if k == "envelope":
        return f"sheet.envelope()   # {_n(f.width)} × {_n(f.height)} × {_n(f.depth)}"
    if k == "hole":
        return _hole_line(f)
    if k == "boss":
        return f'sheet.diameter(diameter={_n(f.diameter)}, at={_pt(f.frame.origin)}, axis="{f.frame.axis}")'
    if k == "step":
        return (
            f"sheet.step(diameter={_n(f.diameter)}, length={_n(f.length)}, "
            f'at={_pt(f.frame.origin)}, axis="{f.frame.axis}")'
        )
    if k == "slot":
        return (
            f"sheet.slot(width={_n(f.width)}, length={_n(f.length)}, "
            f'long_axis="{f.long_axis}", width_axis="{f.width_axis}", '
            f"lo={_n(f.lo)}, hi={_n(f.hi)}, w_center={_n(f.w_center)})"
        )
    if k == "pattern":
        m = f.member
        arr = {
            "bolt_circle": f"bcd={_n(f.bcd)}" if f.bcd else "",
            "linear": f"pitch={_n(f.pitch)}" if f.pitch else "",
            "grid": (
                f"grid=({_n(f.grid[0])}, {_n(f.grid[1])}), rows={f.rows}, cols={f.cols}"
                if f.grid
                else ""
            ),
        }.get(f.pattern, "")
        return (
            f"sheet.pattern(hole(diameter={_n(m.diameter)}, at={_pt(m.frame.origin)}, "
            f'axis="{m.frame.axis}"), kind="{f.pattern}", count={f.count}'
            + (f", {arr}" if arr else "")
            + ")"
        )
    # kinds with no declarative verb yet — the auto-pass still dimensions them.
    return f"# {k} @ {_pt(f.frame.origin)} — auto-dimensioned (no declarative verb yet)"


def _needs_section(model) -> bool:
    return any(
        f.kind == "hole" and f.frame.axis == "z" and (f.cbore or f.spotface or not f.through)
        for f in model.features
    )


_HEADER = '''"""Editable drawing — generated by draftwright (declarative Sheet DSL).

Each line below declares one feature. Comment a line out to drop that feature; edit a
value freely; chain .tolerance(lo, hi) / .fit("H7") onto any diameter. Then re-run:
    uv run python {stem}.py

The values are DETECTED off the geometry (honest for a STEP / recovered solid). If you
built the part yourself, wire your object into the `part = …` seam and swap a numbered
line for a reference — e.g.  sheet.hole(my_bore)  — to read the size off the object.
"""'''


def emit_sheet_script(model, part_expr: str, stem: str, *, title: str, number: str) -> str:
    """The generated declarative ``Sheet`` script text for a detected *model*.

    *part_expr* is the Python that binds ``part`` (a STEP ``import_step`` or a ``part = …``
    seam); *stem* is the output basename the script exports to."""
    needs_hole = any(f.kind in ("hole", "pattern") for f in model.features)
    lines = [
        _HEADER.format(stem=stem),
        "from draftwright import Sheet",
        *(["from draftwright.model import hole"] if needs_hole else []),
        "",
        part_expr,
        "",
        f"sheet = Sheet(part, title={title!r}, number={number!r})",
        "",
        "# ── Features (each line is one declared feature) ──────────────────────────────",
        *(_feature_line(f) for f in model.features),
        "",
        "# ── Views ─────────────────────────────────────────────────────────────────────",
        "# front / plan / side / iso are always produced.",
    ]
    if _needs_section(model):
        lines.append("# Section A–A auto-triggers from the counterbore/blind bore above.")
    lines += ["", f"sheet.export({stem!r})"]
    return "\n".join(lines) + "\n"


def generate_sheet_script(
    step_file: str | Shape,
    out: str | None = None,
    *,
    title: str | None = None,
    number: str = "DWG-001",
) -> str:
    """Write a declarative ``Sheet``-DSL script for *step_file* (a STEP path or a build123d
    object). Returns the path to the generated ``.py``. The mode-3 declarative counterpart of
    :func:`draftwright.builder.generate_script` (which emits the imperative reconstruction)."""
    is_shape = isinstance(step_file, Shape)
    stem = out or ("drawing" if is_shape else Path(step_file).stem)
    for _ext in (".py", ".svg", ".dxf"):
        if stem.endswith(_ext):
            stem = stem[: -len(_ext)]
            break
    title = title or (Path(stem).name.replace("_", " ").upper() if not is_shape else "DRAWING")

    if is_shape:
        part_expr = "part = ...   # ← wire in your build123d object (built above)"
    else:
        part_expr = f"from build123d import import_step\npart = import_step({str(step_file)!r})"

    model = detect_part_model(step_file)
    script = emit_sheet_script(model, part_expr, stem, title=title, number=number)
    py_path = f"{stem}.py"
    Path(py_path).write_text(script)
    return py_path
